{% set name = "itmlogic" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f189d334bc8bfbf17718812c3f3943fa0650300af5b77e9bcd4c4fc193f4af1d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools_scm

test:
  imports:
    - itmlogic

about:
  home: https://github.com/edwardoughton/itmlogic
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Longley-Rice irregular terrain propagation model
  doc_url: https://pypi.org/project/itmlogic/#description
  dev_url: https://github.com/edwardoughton/itmlogic

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - winstonjhoyle
    - Tata17
