{% set name = "itmlogic" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30652f80779b441701d1733c6a0912bcecdd9504d746500fc01a40e4166fb50e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools_scm

test:
  imports:
    - itmlogic

about:
  home: https://github.com/edwardoughton/itmlogic
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Longley-Rice irregular terrain propagation model"
  doc_url: https://pypi.org/project/itmlogic/#description
  dev_url: https://github.com/edwardoughton/itmlogic

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - winstonjhoyle
    - Tata17
